name: 🔍 Lint / Type Checks

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install tools & dependencies
        uses: ./.github/actions/install

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Generate virtual modules
        run: pnpm sync

      - name: TypeScript check
        run: pnpm check:types

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: ESLint check
        run: pnpm check:lint
